# Generated by Django 4.1.5 on 2023-02-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0002_rename_constructionsiteid_constructionsitedetails_constructionsiteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourcampdetails',
            old_name='LabourCampID',
            new_name='LabourCampId',
        ),
    ]
