# Generated by Django 4.1.5 on 2023-02-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0003_rename_labourcampid_labourcampdetails_labourcampid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilitation',
            name='livelihoodSupportPhotograph',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='tenamentsPhotograph',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='trainingPhotograph',
        ),
        migrations.CreateModel(
            name='RehabilitationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livelihoodSupportPhotograph', models.ImageField(blank=True, null=True, upload_to='rehabitation/livelihoodSupportPhotograph/')),
                ('trainingPhotograph', models.ImageField(blank=True, null=True, upload_to='rehabitation/trainingPhotograph/')),
                ('tenamentsPhotograph', models.ImageField(blank=True, null=True, upload_to='rehabitation/tenamentsPhotograph/')),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='rehabitation/Rehabitationphotographs/')),
                ('RehabilitationID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RehabilitationImages', to='SocialMonitoring.rehabilitation')),
            ],
        ),
    ]
