# Generated by Django 4.1.5 on 2023-02-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0004_remove_rehabilitation_livelihoodsupportphotograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='isShiftingAllowance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
