# Generated by Django 4.1.5 on 2023-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0005_alter_rehabilitation_isshiftingallowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='isLivelihoodSupport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='isTraining',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
