# Generated by Django 4.1.5 on 2023-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0006_alter_rehabilitation_islivelihoodsupport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='livelihoodSupportPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/livelihoodSupportPhotograph/'),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/Rehabitationphotographs/'),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='tenamentsPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/tenamentsPhotograph/'),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='trainingPhotograph',
            field=models.ImageField(blank=True, null=True, upload_to='rehabitation/trainingPhotograph/'),
        ),
        migrations.DeleteModel(
            name='RehabilitationImages',
        ),
    ]
