# Generated by Django 4.1.5 on 2023-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0007_rehabilitation_livelihoodsupportphotograph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='categoryOfPap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
