# Generated by Django 4.1.5 on 2023-07-20 07:00

import SocialMonitoring.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0008_rehabilitation_categoryofpap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[SocialMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[SocialMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='pap',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[SocialMonitoring.models.validate_location_precision]),
        ),
    ]
