# Generated by Django 4.1.5 on 2023-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0009_alter_constructionsitedetails_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='barricadingCondition',
        ),
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='barricadingPhotograph',
        ),
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='barricadingRemarks',
        ),
        migrations.RemoveField(
            model_name='constructionsitedetails',
            name='isbarricading',
        ),
    ]
