# Generated by Django 4.1.5 on 2023-08-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0010_remove_constructionsitedetails_barricadingcondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='presentPhotograp',
            new_name='presentPhotograph',
        ),
    ]
