# Generated by Django 4.1.5 on 2023-08-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0011_rename_presentphotograp_pap_presentphotograph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionsitedetails',
            old_name='isSignagesLabeling',
            new_name='isSignagesLabelingCheck',
        ),
    ]
