# Generated by Django 4.1.5 on 2023-08-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0012_rename_issignageslabeling_constructionsitedetails_issignageslabelingcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionsitedetails',
            old_name='isDrinkingWater',
            new_name='isDrinkingWaterCheck',
        ),
    ]
