# Generated by Django 4.1.5 on 2023-08-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0013_rename_isdrinkingwater_constructionsitedetails_isdrinkingwatercheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pap',
            old_name='typeOfAsset',
            new_name='typeOfStructure',
        ),
        migrations.RenameField(
            model_name='rehabilitation',
            old_name='typeOfTenaments',
            new_name='typeOfStructure',
        ),
    ]
