# Generated by Django 4.1.5 on 2023-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0014_rename_typeofasset_pap_typeofstructure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='legalDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pap',
            name='presentPhotograph',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
