# Generated by Django 4.1.5 on 2023-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0015_alter_pap_legaldocuments_alter_pap_presentphotograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pap',
            name='presentPhotograph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
