# Generated by Django 4.1.5 on 2023-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0016_alter_pap_presentphotograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='livelihoodSupportPhotograph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='tenamentsPhotograph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rehabilitation',
            name='trainingPhotograph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
