# Generated by Django 4.1.5 on 2023-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0017_alter_rehabilitation_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
