# Generated by Django 4.1.5 on 2023-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0018_alter_labourcamp_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='documents',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='genralphotographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
