# Generated by Django 4.1.5 on 2023-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0019_alter_constructionsitedetails_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
