# Generated by Django 4.1.5 on 2023-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0021_alter_labourcamp_availabilityofdoctorphotographs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='documents',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='remarks',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
