# Generated by Django 4.1.5 on 2023-09-11 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0024_alter_labourcamp_drinkingwaterphotographs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='availabilityOfDoctorPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='demarkationOfPathwaysPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='fireExtinguishPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='firstAidKitPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='kitchenAreaPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='regularHealthCheckupPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='roomsOrDomsPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='segregationOfWastePhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='signagesLabelingPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
