# Generated by Django 4.1.5 on 2023-09-11 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0025_alter_labourcamp_availabilityofdoctorphotographs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='drinkingWaterPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None), size=None),
        ),
    ]
