# Generated by Django 4.1.5 on 2023-09-11 11:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0027_alter_labourcamp_drinkingwaterphotographs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcamp',
            name='firstAidKitPhotographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labourcamp',
            name='toiletPhotograph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
