# Generated by Django 4.1.5 on 2023-09-11 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0028_alter_labourcamp_firstaidkitphotographs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='availabilityOfDoctorPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='demarkationOfPathwaysPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='drinkingWaterPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='firstAidKitPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='genralphotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='regularHealthCheckupPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='signagesLabelingPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionsitedetails',
            name='toiletPhotograph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
    ]
