# Generated by Django 4.1.5 on 2023-09-12 05:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialMonitoring', '0030_alter_constructionsitedetails_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourcampdetails',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labourcampdetails',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labourcampdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labourcampDetails_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
