# Generated by Django 4.1.5 on 2023-09-12 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0031_labourcampdetails_capacity_labourcampdetails_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourcampdetails',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
