# Generated by Django 4.1.5 on 2024-02-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0032_alter_labourcampdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
