# Generated by Django 4.1.5 on 2024-02-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0033_pap_firstname_pap_lastname_pap_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='cadastralMapDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pap',
            name='cadastralMapID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
