# Generated by Django 4.1.5 on 2024-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0034_pap_cadastralmapdocuments_pap_cadastralmapid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='agreedUpon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='alternateAccomodationLocationDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='alternateAccomodationRelocationAllowance',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='alternateAccomodationStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='cashCompensationAmount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='cashCompensationStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='commercialUnitLocationDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='commercialUnitRelocationAllowance',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='commercialUnitStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='landProvidedArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='landProvidedAreaLocationDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='landProvidedStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
