# Generated by Django 4.1.5 on 2024-03-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0035_pap_firstname_pap_lastname_rehabilitation_agreedupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitation',
            name='ID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation', to='SocialMonitoring.pap'),
        ),
    ]
