# Generated by Django 4.1.5 on 2024-05-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0038_pap_cadastralmapdocuments2_pap_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='cadastralMapDocuments',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='cadastralMapDocuments2',
        ),
    ]
