# Generated by Django 4.1.5 on 2024-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0040_pap_cadastralmapdocuments_pap_firstname_pap_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='legalDocuments',
        ),
    ]
