# Generated by Django 4.1.5 on 2024-05-23 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0041_remove_pap_legaldocuments_pap_firstname_pap_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='legalDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
