# Generated by Django 4.1.5 on 2024-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0042_pap_firstname_pap_lastname_pap_legaldocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='presentPhotograph',
        ),
    ]
