# Generated by Django 4.1.5 on 2024-05-23 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0044_pap_firstname_pap_lastname_pap_presentphotograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='pap',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
