# Generated by Django 4.1.5 on 2024-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0046_pap_firstname_pap_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pap',
            name='nameOfPAP',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='PAPName',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='alternateAccomodationLocationDetails',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='alternateAccomodationRelocationAllowance',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='alternateAccomodationStatus',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='areaOfTenament',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='cashCompensation',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='cashCompensationStatus',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='commercialUnitLocationDetails',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='commercialUnitRelocationAllowance',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='commercialUnitStatus',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='landProvidedAreaLocationDetails',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='landProvidedStatus',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='livelihoodSupportCondition',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='livelihoodSupportPhotograph',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='livelihoodSupportRemarks',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='tenamentsPhotograph',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='trainingCondition',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='trainingPhotograph',
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='alternateAccomodationArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='commercialUnitArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='processStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='rehabLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
