# Generated by Django 4.1.5 on 2024-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0047_remove_pap_nameofpap_remove_rehabilitation_papname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcamp',
            name='firstAidKitPhotographs',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='cadastralMapDocuments',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='legalDocuments',
        ),
        migrations.RemoveField(
            model_name='pap',
            name='presentPhotograph',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='photographs',
        ),
    ]
