# Generated by Django 4.1.5 on 2024-07-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0048_remove_labourcamp_firstaidkitphotographs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitation',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
