# Generated by Django 4.1.5 on 2024-07-05 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0049_rehabilitation_firstname_rehabilitation_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourcamp',
            name='firstAidKitPhotographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pap',
            name='cadastralMapDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='pap',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='pap',
            name='legalDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='pap',
            name='presentPhotograph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
    ]
