# Generated by Django 4.1.5 on 2024-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0050_labourcamp_firstaidkitphotographs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehabilitation',
            name='alternateAccomodationArea',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='categoryOfPap',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='commercialUnitArea',
        ),
        migrations.RemoveField(
            model_name='rehabilitation',
            name='landProvidedArea',
        ),
        migrations.AddField(
            model_name='rehabilitation',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
