# Generated by Django 4.1.5 on 2024-09-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMonitoring', '0051_remove_rehabilitation_alternateaccomodationarea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourcamp',
            name='distanceFromSite',
        ),
        migrations.RemoveField(
            model_name='labourcamp',
            name='transportationFacilityCondition',
        ),
    ]
