# Generated by Django 4.1.5 on 2023-01-27 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_ca10'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package08Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package08Alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package09Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package09Alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package10Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package10Alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package11Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package11Alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package12Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package12Alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package54Alignment',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32643)),
            ],
            options={
                'db_table': 'Package54Alignment',
                'managed': False,
            },
        ),
    ]
