# Generated by Django 4.1.5 on 2023-01-27 09:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_delete_ca10'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
    ]
