# Generated by Django 4.1.5 on 2023-02-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_station'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package08alignment',
            table='package08Alignment',
        ),
    ]
