# Generated by Django 4.1.5 on 2023-02-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_alter_package08alignment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='package09alignment',
            table='package09Alignment',
        ),
        migrations.AlterModelTable(
            name='package10alignment',
            table='package10Alignment',
        ),
        migrations.AlterModelTable(
            name='package11alignment',
            table='package11Alignment',
        ),
        migrations.AlterModelTable(
            name='package12alignment',
            table='package12Alignment',
        ),
        migrations.AlterModelTable(
            name='package54alignment',
            table='package54Alignment',
        ),
    ]
