# Generated by Django 4.1.5 on 2023-08-22 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_alter_package09alignment_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metroline4',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.FloatField(blank=True, null=True)),
                ('extrude', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('draworder', models.FloatField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'metroline4',
                'managed': False,
            },
        ),
    ]
