# Generated by Django 4.1.5 on 2023-08-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0008_metroline4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metroline4',
        ),
    ]
