# Generated by Django 4.1.5 on 2023-08-23 05:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0009_delete_metroline4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MmrdaNew',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('field_gid', models.DecimalField(blank=True, db_column='__gid', decimal_places=65535, max_digits=65535, null=True)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('layer', models.CharField(blank=True, max_length=254, null=True)),
                ('path', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_new',
                'managed': False,
            },
        ),
    ]
