# Generated by Django 4.1.2 on 2022-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0007_rename_planted_details_treemanagment_planteddetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noise',
            old_name='Monitoring_Period',
            new_name='monitoringPeriod',
        ),
        migrations.RenameField(
            model_name='noise',
            old_name='noise_level',
            new_name='noiseLevel',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='quality_of_water',
            new_name='qualityOfWater',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='source_of_water',
            new_name='sourceOfWater',
        ),
        migrations.AddField(
            model_name='water',
            name='waterDisposal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='planted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='transplanted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
