# Generated by Django 4.1.2 on 2022-12-21 10:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0009_air_month_materialsourcing_month_noise_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsourcing',
            name='source',
            field=models.CharField(blank=True, choices=[('Quarry', 'Quarry'), ('Factory', 'Factory'), ('Casting Yard', 'Casting Yard'), ('Local Vendor', 'Local Vendor'), ('Others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='typeOfMaterial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='wasteHandlingLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
