# Generated by Django 4.1.2 on 2022-12-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0010_materialsourcing_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='air',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='air',
            name='trends',
        ),
        migrations.AddField(
            model_name='air',
            name='AQI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='NOx',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='O3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='PM10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='SO2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='standardNOx',
            field=models.PositiveIntegerField(blank=True, default=80.0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='standardO3',
            field=models.PositiveIntegerField(blank=True, default=100.0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='standardPM10',
            field=models.PositiveIntegerField(blank=True, default=100.0, null=True),
        ),
        migrations.AddField(
            model_name='air',
            name='standardSO2',
            field=models.PositiveIntegerField(blank=True, default=80.0, null=True),
        ),
    ]
