# Generated by Django 4.1.2 on 2022-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0011_remove_air_deviation_remove_air_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='Remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
