# Generated by Django 4.1.2 on 2022-12-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0012_air_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsourcing',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='materialsourcing_documents'),
        ),
        migrations.AddField(
            model_name='materialsourcing',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='materialsourcing_photographs/'),
        ),
        migrations.AddField(
            model_name='materialsourcing',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='waste_documents'),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='photographs',
            field=models.ImageField(blank=True, null=True, upload_to='waste_photographs/'),
        ),
    ]
