# Generated by Django 4.1.2 on 2022-12-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0013_materialsourcing_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemanagment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
