# Generated by Django 4.1.2 on 2022-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0014_treemanagment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='AQI',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='NOx',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='O3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='PM10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='SO2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='standardNOx',
            field=models.FloatField(blank=True, default=80.0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='standardO3',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='standardPM10',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='standardSO2',
            field=models.FloatField(blank=True, default=80.0, null=True),
        ),
    ]
