# Generated by Django 4.1.2 on 2022-12-28 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0015_alter_air_aqi_alter_air_nox_alter_air_o3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treemanagment',
            old_name='botanicalName',
            new_name='CbotonicalName',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='commanName',
            new_name='Ccondition',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='condition',
            new_name='Cname',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='management',
            new_name='EbotanicalName',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='plantedDetails',
            new_name='EcommanName',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='transplantedDetails',
            new_name='Econdition',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='remarks',
            new_name='Eremarks',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='treecutDetails',
            new_name='EtreeID',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='planted',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='surveyDate',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='surveyTime',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='transplanted',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='tree_no',
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cdocuments',
            field=models.FileField(blank=True, null=True, upload_to='newTree_documents/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Clocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cphotographs',
            field=models.ImageField(blank=True, null=True, upload_to='newTree_photographs/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cremarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Edocuments',
            field=models.FileField(blank=True, null=True, upload_to='existingTree_documents/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Ephotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Existingtree_photos/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='actionTaken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
