# Generated by Django 4.1.2 on 2022-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0016_rename_botanicalname_treemanagment_cbotonicalname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemanagment',
            name='actionTaken',
            field=models.CharField(blank=True, choices=[('Transplanted', 'Transplanted'), ('New Tree Planted', 'New Tree Planted'), ('No action Taken', 'No action Taken')], max_length=255, null=True),
        ),
    ]
