# Generated by Django 4.1.2 on 2023-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0017_alter_treemanagment_actiontaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialsourcing',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treemanagment',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='quarter',
            field=models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True),
        ),
    ]
