# Generated by Django 4.1.5 on 2023-01-04 13:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0018_alter_air_quarter_alter_materialsourcing_quarter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialManegmanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255, null=True)),
                ('packages', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('dateOfConduct', models.DateField(blank=True, null=True)),
                ('typeOfMaterial', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, choices=[('Quarry', 'Quarry'), ('Factory', 'Factory'), ('Casting Yard', 'Casting Yard'), ('Local Vendor', 'Local Vendor'), ('Others', 'Others')], max_length=255, null=True)),
                ('sourceOfQuarry', models.CharField(blank=True, choices=[('Mines', 'Mines'), ('Blast', 'Blast')], max_length=255, null=True)),
                ('storageLocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('materialstorageCondition', models.CharField(blank=True, choices=[('Good', 'Good'), ('Average', 'Average'), ('Poor', 'poor')], max_length=255, null=True)),
                ('materialstoragePhotograph', models.ImageField(blank=True, null=True, upload_to='MaterialManegment/materailStorage_Photograph')),
                ('approvals', models.FileField(blank=True, null=True, upload_to='')),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='MaterialManegment/materialsourcing_photographs/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='MaterialManegment/materialsourcing_documents')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialSourcing',
        ),
    ]
