# Generated by Django 4.1.5 on 2023-01-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0021_rename_storagetypeofmaterial_materialmanegmanet_materialstoragetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
        migrations.RenameField(
            model_name='materialmanegmanet',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
        migrations.RenameField(
            model_name='noise',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
        migrations.RenameField(
            model_name='treemanagment',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='dateOfConduct',
            new_name='dateOfMonitoring',
        ),
    ]
