# Generated by Django 4.1.5 on 2023-01-07 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnvMonitoring', '0023_air_user_materialmanegmanet_user_noise_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waters', to=settings.AUTH_USER_MODEL),
        ),
    ]
