# Generated by Django 4.1.5 on 2023-01-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0024_water_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemanagment',
            name='CbotonicalName',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Ccondition',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Cdocuments',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Clocation',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Cname',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Cphotographs',
        ),
        migrations.RemoveField(
            model_name='treemanagment',
            name='Cremarks',
        ),
    ]
