# Generated by Django 4.1.5 on 2023-01-16 11:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0025_remove_treemanagment_cbotonicalname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemanagment',
            name='CbotonicalName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Ccondition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cdocuments',
            field=models.FileField(blank=True, null=True, upload_to='newTree_documents/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Clocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cphotographs',
            field=models.ImageField(blank=True, null=True, upload_to='newTree_photographs/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cremarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
