# Generated by Django 4.1.5 on 2023-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0027_remove_treemanagment_cdocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemanagment',
            name='Cdocuments',
            field=models.FileField(blank=True, null=True, upload_to='newTree_documents/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Cphotographs',
            field=models.ImageField(blank=True, null=True, upload_to='newTree_photographs/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Edocuments',
            field=models.FileField(blank=True, null=True, upload_to='existingTree_documents/'),
        ),
        migrations.AddField(
            model_name='treemanagment',
            name='Ephotographs',
            field=models.ImageField(blank=True, null=True, upload_to='Existingtree_photos/'),
        ),
        migrations.DeleteModel(
            name='TreePhotographs',
        ),
    ]
