# Generated by Django 4.1.5 on 2023-01-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0028_treemanagment_cdocuments_treemanagment_cphotographs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePhotographs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ephotographs', models.ImageField(blank=True, null=True, upload_to='Existingtree_photos/')),
                ('Cphotographs', models.ImageField(blank=True, null=True, upload_to='newTree_photographs/')),
                ('Tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TreeManagment', to='EnvMonitoring.treemanagment')),
            ],
        ),
    ]
