# Generated by Django 4.1.5 on 2023-01-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0029_treephotographs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreePhotographs',
        ),
    ]
