# Generated by Django 4.1.5 on 2023-01-19 07:39

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnvMonitoring', '0030_delete_treephotographs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingTreeManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('packages', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('dateOfMonitoring', models.DateField(blank=True, null=True)),
                ('treeID', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('commanName', models.CharField(blank=True, max_length=255, null=True)),
                ('botanicalName', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('actionTaken', models.CharField(blank=True, max_length=255, null=True)),
                ('noOfTreeCut', models.IntegerField(blank=True, null=True)),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='Existingtree_photos/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='existingTree_documents/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tree_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewTreeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('packages', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfMonitoring', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('commanName', models.CharField(blank=True, max_length=255, null=True)),
                ('botanicalName', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='newTree_photographs/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='newTree_documents/')),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExistingTreeManagment', to='EnvMonitoring.existingtreemanagment')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='newTree_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TreeManagment',
        ),
    ]
