# Generated by Django 4.1.5 on 2023-01-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0031_existingtreemanagment_newtreemanagement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noise',
            old_name='dateOfMonitoring',
            new_name='dateOfMonitoringThree',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='dateOfMonitoring',
            new_name='dateOfMonitoringTwo',
        ),
    ]
