# Generated by Django 4.1.5 on 2023-07-20 07:00

import EnvMonitoring.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0032_rename_dateofmonitoring_noise_dateofmonitoringthree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='existingtreemanagment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='materialmanegmanet',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='noise',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='water',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[EnvMonitoring.models.validate_location_precision]),
        ),
    ]
