# Generated by Django 4.1.5 on 2023-08-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0033_alter_air_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialmanegmanet',
            old_name='materialstoragePhotograph',
            new_name='materialStoragePhotograph',
        ),
        migrations.RemoveField(
            model_name='materialmanegmanet',
            name='materialstorageCondition',
        ),
    ]
