# Generated by Django 4.1.5 on 2023-08-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0034_rename_materialstoragephotograph_materialmanegmanet_materialstoragephotograph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmanegmanet',
            name='materialStorageCondition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
