# Generated by Django 4.1.5 on 2023-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0036_alter_noise_noiselevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='PM10',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
