# Generated by Django 4.1.5 on 2023-08-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0037_alter_air_pm10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtreemanagement',
            name='tree',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExistingTreeManagment', to='EnvMonitoring.existingtreemanagment'),
        ),
    ]
