# Generated by Django 4.1.5 on 2023-08-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0038_alter_newtreemanagement_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='NOx',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='O3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='SO2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
