# Generated by Django 4.1.5 on 2023-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0039_alter_air_nox_alter_air_o3_alter_air_so2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='AQI',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='Remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
