# Generated by Django 4.1.5 on 2023-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0043_alter_newtreemanagement_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastetreatments',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wastetreatments',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
