# Generated by Django 4.1.5 on 2023-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0044_alter_wastetreatments_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmanegmanet',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialmanegmanet',
            name='materialStoragePhotograph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialmanegmanet',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
