# Generated by Django 4.1.5 on 2023-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0045_alter_materialmanegmanet_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmanegmanet',
            name='approvals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
