# Generated by Django 4.1.5 on 2024-01-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0047_air_co_noise_monitoringperiod_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='CO',
        ),
    ]
