# Generated by Django 4.1.5 on 2024-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0048_remove_air_co'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='CO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
