# Generated by Django 4.1.5 on 2024-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0049_air_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='O3',
        ),
        migrations.RemoveField(
            model_name='air',
            name='standardNOx',
        ),
        migrations.RemoveField(
            model_name='air',
            name='standardO3',
        ),
        migrations.RemoveField(
            model_name='air',
            name='standardPM10',
        ),
        migrations.RemoveField(
            model_name='air',
            name='standardSO2',
        ),
        migrations.AddField(
            model_name='air',
            name='PM2_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='AQI',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='CO',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='NOx',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='PM10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='air',
            name='SO2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
