# Generated by Django 4.1.5 on 2024-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0051_water_aluminum_water_cadmium_water_calcium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
