# Generated by Django 4.1.5 on 2024-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0052_air_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='noise',
            name='isWithinLimit_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noise',
            name='isWithinLimit_night',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
