# Generated by Django 4.1.5 on 2024-02-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0053_noise_iswithinlimit_day_noise_iswithinlimit_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='WQI',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
