# Generated by Django 4.1.5 on 2024-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0054_water_wqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastetreatments',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='waste_documents/'),
        ),
    ]
