# Generated by Django 4.1.5 on 2024-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0057_wastetreatments_filterqnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetreatments',
            name='GISPermitsTransportationDocuments',
            field=models.FileField(blank=True, null=True, upload_to='waste_documents/GISPermitsTransportation'),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='isGISPermitsTransportation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
