# Generated by Django 4.1.5 on 2024-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0058_wastetreatments_gispermitstransportationdocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetreatments',
            name='TransportationVechicalHasPermissionDocuments',
            field=models.FileField(blank=True, null=True, upload_to='waste_documents/'),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='isTransportationVechicalHasPermission',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
