# Generated by Django 4.1.5 on 2024-06-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0059_wastetreatments_transportationvechicalhaspermissiondocuments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='noiseLevel_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noise',
            name='noiseLevel_night',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
