# Generated by Django 4.1.5 on 2024-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0060_alter_noise_noiselevel_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingtreemanagment',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='existingtreemanagment',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='materialmanegmanet',
            name='approvals',
        ),
        migrations.RemoveField(
            model_name='materialmanegmanet',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='materialmanegmanet',
            name='materialStoragePhotograph',
        ),
        migrations.RemoveField(
            model_name='materialmanegmanet',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='newtreemanagement',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='newtreemanagement',
            name='photographs',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='GISPermitsTransportationDocuments',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='TransportationVechicalHasPermissionDocuments',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='wastetreatments',
            name='photographs',
        ),
    ]
