# Generated by Django 4.1.5 on 2024-07-05 06:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0061_remove_existingtreemanagment_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingtreemanagment',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='existingtreemanagment',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='materialStoragePhotograph',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='newtreemanagement',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='newtreemanagement',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='GISPermitsTransportationDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='TransportationVechicalHasPermissionDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
    ]
