# Generated by Django 4.1.5 on 2024-09-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0062_existingtreemanagment_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noise',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
