# Generated by Django 4.1.5 on 2024-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0063_noise_place_location_water_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetreatments',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
