# Generated by Django 4.1.5 on 2024-09-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0064_wastetreatments_place_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='place_location',
            new_name='Waste_collecting_location',
        ),
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='wastehandling',
            new_name='Waste_disposing_location',
        ),
        migrations.AddField(
            model_name='existingtreemanagment',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='material_source_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialmanegmanet',
            name='material_storage_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newtreemanagement',
            name='place_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
