# Generated by Django 4.1.5 on 2024-09-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0065_rename_place_location_wastetreatments_waste_collecting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastetreatments',
            name='wastehandling',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
