# Generated by Django 4.1.5 on 2024-09-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0066_wastetreatments_wastehandling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastetreatments',
            name='wastehandling',
        ),
    ]
