# Generated by Django 4.1.5 on 2024-09-21 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0067_remove_wastetreatments_wastehandling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastetreatments',
            name='wasteHandlingLocation',
        ),
        migrations.AddField(
            model_name='wastetreatments',
            name='waste_handlingLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
