# Generated by Django 4.1.5 on 2024-09-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0068_remove_wastetreatments_wastehandlinglocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastetreatments',
            name='wastetype',
        ),
    ]
