# Generated by Django 4.1.5 on 2024-09-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0069_remove_wastetreatments_wastetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='Waste_collecting_location',
            new_name='waste_collecting_location',
        ),
    ]
