# Generated by Django 4.1.5 on 2024-09-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnvMonitoring', '0070_rename_waste_collecting_location_wastetreatments_waste_collecting_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastetreatments',
            old_name='Waste_disposing_location',
            new_name='waste_disposing_location',
        ),
    ]
