# Generated by Django 4.1.2 on 2023-01-03 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='occupationalHealthSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, choices=[('January-March', 'January-March'), ('April-June', 'April-June'), ('July-September', 'July-September'), ('October-December', 'October-December')], max_length=255, null=True)),
                ('packages', models.CharField(blank=True, choices=[('CA-08', 'CA-08'), ('CA-09', 'CA-09'), ('CA-10', 'CA-10'), ('CA-11', 'CA-11'), ('CA-12', 'CA-12'), ('CA-54', 'CA-54')], max_length=255, null=True)),
                ('dateOfMonitoring', models.DateField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('JoiningMedicalCheckup', models.BooleanField(blank=True, null=True)),
                ('PPEkit', models.BooleanField(blank=True)),
                ('TrainingToWorkers', models.BooleanField(blank=True)),
                ('HouseKeeping', models.BooleanField(blank=True)),
                ('PowerSupplySystem', models.BooleanField(blank=True)),
                ('AssemblyArea', models.BooleanField(blank=True)),
                ('AmbulanceArrangement', models.BooleanField(blank=True)),
                ('ToiletFacility', models.BooleanField(blank=True)),
                ('SafeMomentPasage', models.BooleanField(blank=True)),
                ('MaterialKeepingPractice', models.CharField(blank=True, choices=[('Safe', 'Safe'), ('Unsafe', 'Unsafe'), ('Need Improvements', 'Need Improvements')], max_length=255, null=True)),
                ('accidental_check', models.BooleanField(blank=True)),
                ('SafetyGearStatus', models.BooleanField(blank=True)),
                ('Barricading', models.BooleanField(blank=True)),
                ('NatureOfAccident', models.CharField(blank=True, max_length=255, null=True)),
                ('TypeOfIncident', models.CharField(blank=True, choices=[('Reportable Accident', 'Reportable Accident'), ('Reportable Non-Fatal Accident', 'Reportable Non-Fatal Accident'), ('First Aid Cases', 'First Aid Cases'), ('Dangerous Occurrences', 'Dangerous Occurrences'), ('Man Days lost', 'Man Days Lost'), ('Major (Road accident)', 'Major (Road accident)'), ('Road Incident', 'Road Incident'), ('Tree Broken', 'Tree Broken'), ('Natural Death', 'Natural Death'), ('3rd Party Incident', 'Third Party Incident')], max_length=255, null=True)),
                ('IncidentDetails', models.TextField(blank=True, max_length=255, null=True)),
                ('IdentifiedCauseOfIncident', models.CharField(blank=True, max_length=255, null=True)),
                ('Outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('CompensationPaid', models.CharField(blank=True, max_length=255, null=True)),
                ('photographs', models.ImageField(blank=True, null=True, upload_to='photographs/')),
                ('Remarks', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
