# Generated by Django 4.1.2 on 2023-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0004_occupationalhealthsafety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='CompensationPaid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
