# Generated by Django 4.1.5 on 2023-01-06 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0006_alter_occupationalhealthsafety_photographs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traning',
            name='traning_id',
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='occupational_health_safety_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographs',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photograph_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traning',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='training_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='MaterialKeepingPractice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='TypeOfIncident',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='packages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='quarter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traning',
            name='traninig_initiated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
