# Generated by Django 4.1.5 on 2023-01-07 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0007_remove_traning_traning_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='AmbulanceArrangement',
            new_name='accidentalCheck',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='AssemblyArea',
            new_name='ambulanceArrangement',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='Barricading',
            new_name='assemblyArea',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='HouseKeeping',
            new_name='barricading',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='CompensationPaid',
            new_name='compensationPaid',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='PPEkit',
            new_name='houseKeeping',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='IdentifiedCauseOfIncident',
            new_name='identifiedCauseOfIncident',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='IncidentDetails',
            new_name='incidentDetails',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='JoiningMedicalCheckup',
            new_name='joiningMedicalCheckup',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='MaterialKeepingPractice',
            new_name='materialKeepingPractice',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='NatureOfAccident',
            new_name='natureOfAccident',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='Outcome',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='PowerSupplySystem',
            new_name='powerSupplySystem',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='SafeMomentPasage',
            new_name='ppeKit',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='Remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='SafetyGearStatus',
            new_name='safeMomentPassage',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='ToiletFacility',
            new_name='safetyGearStatus',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='TrainingToWorkers',
            new_name='toiletFacility',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='accidental_check',
            new_name='trainingToWorkers',
        ),
        migrations.RenameField(
            model_name='occupationalhealthsafety',
            old_name='TypeOfIncident',
            new_name='typeOfIncident',
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='traning',
            name='dateOfMonitoring',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traning',
            name='packages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traning',
            name='quarter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traning',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
