# Generated by Django 4.1.5 on 2023-01-11 04:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_rename_ambulancearrangement_occupationalhealthsafety_accidentalcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
