# Generated by Django 4.1.5 on 2023-01-12 06:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0009_contactus_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
