# Generated by Django 4.1.5 on 2023-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0011_contactus_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='images',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='contactus/images'),
        ),
    ]
