# Generated by Django 4.1.5 on 2023-01-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0012_alter_contactus_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='images',
        ),
        migrations.CreateModel(
            name='ContactusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, max_length=255, null=True, upload_to='contactus/images')),
                ('contactus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Training.contactus')),
            ],
        ),
    ]
