# Generated by Django 4.1.5 on 2023-01-27 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0013_remove_contactus_images_contactusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShiftingofUtilities', models.BooleanField(default=False)),
                ('RulesOfShiftingofUtilities', models.CharField(default='High tension power line, water supply pipeline, sewer\n                                                                                        line, gas pipeline etc. as per MCGM guide lines', max_length=255)),
                ('ResponsibilityOfShiftingofUtilities', models.CharField(blank=True, max_length=255)),
                ('CurrentStatusOfShiftingofUtilities', models.CharField(blank=True, max_length=255, null=True)),
                ('PermissionForFellingOfTrees', models.BooleanField(default=False)),
                ('RulesOfPermissionForFellingOfTrees', models.CharField(blank=True, max_length=255, null=True)),
                ('ResponsibilityOfPermissionForFellingOfTrees', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusPermissionForFellingOfTrees', models.CharField(blank=True, max_length=255, null=True)),
                ('CRZClearance', models.BooleanField(default=False)),
                ('ResponsibilityOfCRZClearance', models.CharField(blank=True, default='As per CRZ Rules, MOEF&CC.', max_length=255, null=True)),
                ('CurrentStatusCRZClearance', models.CharField(blank=True, max_length=255, null=True)),
                ('ForestClearance', models.BooleanField(default=False)),
                ('ResponsibilityOfForestClearance', models.CharField(blank=True, default='Forest Conservation Act, 1980, amended 1988.', max_length=255, null=True)),
                ('CurrentStatusOfForestClearance', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
