# Generated by Django 4.1.5 on 2023-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0014_preconstructionstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConsenttToEstablishOoperate', models.BooleanField(default=False)),
                ('RulesOfConsenttToEstablishOoperate', models.CharField(default='Air (Prevention and Control of Pollution) Act', max_length=255)),
                ('ResponsibilityOfConsenttToEstablishOoperate', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfConsenttToEstablishOoperate', models.CharField(blank=True, max_length=255, null=True)),
                ('PermissionForSandMiningFromRiverbed', models.BooleanField(default=False)),
                ('RulesOfSandMiningFromRiverbed', models.CharField(default='Environment (Protection) Act', max_length=255)),
                ('ResponsibilityOfSandMiningFromRiverbed', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfSandMiningFromRiverbed', models.CharField(blank=True, max_length=255, null=True)),
                ('PermissionForGroundWaterWithdrawal', models.BooleanField(default=False)),
                ('RulesForGroundWaterWithdrawal', models.CharField(default='Environment (Protection) Act', max_length=255)),
                ('ResponsibilityForGroundWaterWithdrawal', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfGroundWaterWithdrawal', models.CharField(blank=True, max_length=255, null=True)),
                ('AuthorizationForCollectionDisposalManagement', models.BooleanField(default=False)),
                ('RulesForCollectionDisposalManagement', models.CharField(default='Hazardous waste (Management andHandling) Rules', max_length=255)),
                ('ResponsibilityForCollectionDisposalManagement', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfCollectionDisposalManagement', models.CharField(blank=True, max_length=255, null=True)),
                ('AuthorizationForSolidWaste', models.BooleanField(default=False)),
                ('RulesForSolidWaste', models.CharField(default='Municipal Solid waste Rules', max_length=255)),
                ('ResponsibilityOfSolidWaste', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfSolidWaste', models.CharField(blank=True, max_length=255, null=True)),
                ('DisposalOfBituminousAndOtherWaste', models.BooleanField(default=False)),
                ('RulesForDisposalOfBituminousAndOtherWaste', models.CharField(default='Hazardous waste (Management andHandling) Rules', max_length=255)),
                ('ResponsibilityOfDisposalOfBituminousAndOtherWaste', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfDisposalOfBituminousAndOtherWaste', models.CharField(blank=True, max_length=255, null=True)),
                ('ConsentToDisposalOfsewagefromLabourCamps', models.BooleanField(default=False)),
                ('RulesForDisposalOfsewagefromLabourCamps', models.CharField(default='Water (Prevention and Control of Pollution) Act', max_length=255)),
                ('ResponsibilityOfDisposalOfsewagefromLabourCamps', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusOfDisposalOfsewagefromLabourCamps', models.CharField(blank=True, max_length=255, null=True)),
                ('PollutionUnderControlCertificate', models.BooleanField(default=False)),
                ('RulesForPollutionUnderControl', models.CharField(default='Central Motor and Vehicles Act', max_length=255)),
                ('ResponsibilityOfPollutionUnderControl', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusPollutionUnderControl', models.CharField(blank=True, max_length=255, null=True)),
                ('RoofTopRainWaterHarvesting', models.BooleanField(default=False)),
                ('RulesForRoofTopRainWaterHarvesting', models.CharField(default='Central Ground Water Authority (CGWA),Guidelines', max_length=255)),
                ('ResponsibilityOfRoofTopRainWaterHarvesting', models.CharField(blank=True, max_length=255, null=True)),
                ('CurrentStatusRoofTopRainWaterHarvesting', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='RulesOfCRZClearance',
            field=models.CharField(blank=True, default='As per CRZ Rules, MOEF&CC.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='RulesOfForestClearance',
            field=models.CharField(blank=True, default='Forest Conservation Act, 1980, amended 1988.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preconstructionstage',
            name='ResponsibilityOfCRZClearance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preconstructionstage',
            name='ResponsibilityOfForestClearance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
