# Generated by Django 4.1.5 on 2023-01-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0017_constructionstage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusimage',
            name='contactus',
        ),
    ]
