# Generated by Django 4.1.5 on 2023-02-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0018_remove_contactusimage_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusimage',
            old_name='images',
            new_name='images1',
        ),
        migrations.AddField(
            model_name='contactusimage',
            name='contactus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Training.contactus'),
        ),
        migrations.AddField(
            model_name='contactusimage',
            name='images2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='contactus/images'),
        ),
    ]
