# Generated by Django 4.1.5 on 2023-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0020_alter_preconstructionstage_rulesofpermissionforfellingoftrees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupationalhealthsafety',
            name='document',
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='OccupationalHealth&Safety/'),
        ),
    ]
