# Generated by Django 4.1.5 on 2023-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0021_remove_occupationalhealthsafety_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traning',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='traning_photographs/'),
        ),
    ]
