# Generated by Django 4.1.5 on 2023-08-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0022_traning_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traning',
            old_name='conduct_date',
            new_name='conductDate',
        ),
        migrations.RenameField(
            model_name='traning',
            old_name='incharge_person',
            new_name='inchargePerson',
        ),
        migrations.RenameField(
            model_name='traning',
            old_name='no_of_attends',
            new_name='noOfAttends',
        ),
        migrations.RenameField(
            model_name='traning',
            old_name='traning_date',
            new_name='traningDate',
        ),
        migrations.RenameField(
            model_name='traning',
            old_name='traning_title',
            new_name='traningTitle',
        ),
        migrations.RenameField(
            model_name='traning',
            old_name='traninig_initiated_by',
            new_name='traninigInitiatedBy',
        ),
    ]
