# Generated by Django 4.1.5 on 2023-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0023_rename_conduct_date_traning_conductdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traning',
            name='noOfTimesTrainingConducted',
            field=models.IntegerField(default=0),
        ),
    ]
