# Generated by Django 4.1.5 on 2023-08-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0024_traning_nooftimestrainingconducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traning',
            name='description',
        ),
    ]
