# Generated by Django 4.1.5 on 2023-08-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0026_contactus_uploaded_images1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='uploaded_images1',
            new_name='documents',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='uploaded_images2',
            new_name='image',
        ),
    ]
