# Generated by Django 4.1.5 on 2023-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0027_rename_uploaded_images1_contactus_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traning',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traning',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
