# Generated by Django 4.1.5 on 2023-08-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0028_alter_traning_documents_alter_traning_photographs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='photographs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
