# Generated by Django 4.1.5 on 2023-08-23 06:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0029_alter_occupationalhealthsafety_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='incidentLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
