# Generated by Django 4.1.5 on 2023-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0030_occupationalhealthsafety_incidentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='accidentalCheckCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='accidentalCheckRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='ambulanceArrangementCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='ambulanceArrangementRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='assemblyAreaCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='assemblyAreaRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='barricadingCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='barricadingRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='houseKeepingCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='houseKeepingRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='joiningMedicalCheckupCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='joiningMedicalCheckupConditionRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='materialKeepingPracticeCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='materialKeepingPracticeRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='powerSupplySystemCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='powerSupplySystemRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='ppeKitCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='ppeKitRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='safeMomentPassageCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='safeMomentPassageRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='safetyGearStatusCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='safetyGearStatusRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='toiletFacilityCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='toiletFacilityRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='trainingToWorkersCondition',
            field=models.CharField(choices=[('Complied', 'Complied'), ('Not-Complied', 'Not-Complied')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='trainingToWorkersRemarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
