# Generated by Django 4.1.5 on 2024-02-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0031_occupationalhealthsafety_accidentalcheckcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='incidentReportingStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
