# Generated by Django 4.1.5 on 2024-03-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0032_occupationalhealthsafety_incidentreportingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstructionstage',
            name='CRZClearanceDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='ForestClearanceDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='PermissionForFellingOfTreesDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='ShiftingofUtilitiesDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
