# Generated by Django 4.1.5 on 2024-03-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0033_preconstructionstage_crzclearancedocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionstage',
            name='AuthorizationForCollectionDisposalManagementDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='AuthorizationForSolidWasteDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='ConsentToDisposalOfsewagefromLabourCampsDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='ConsenttToEstablishOoperateDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='DisposalOfBituminousAndOtherWasteDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='PermissionForGroundWaterWithdrawalDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='PermissionForSandMiningFromRiverbedDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='PollutionUnderControlCertificateDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='RoofTopRainWaterHarvestingDocuments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
