# Generated by Django 4.1.5 on 2024-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0035_alter_preconstructionstage_crzclearancedocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='manDaysLostCount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='manDaysLostReason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
