# Generated by Django 4.1.5 on 2024-08-03 11:01

import Training.models
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0036_occupationalhealthsafety_mandayslostcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupationalhealthsafety',
            name='incidentLocation',
        ),
        migrations.AlterField(
            model_name='occupationalhealthsafety',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[Training.models.validate_location_precision]),
        ),
        migrations.AlterField(
            model_name='traning',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, validators=[Training.models.validate_location_precision]),
        ),
    ]
