# Generated by Django 4.1.5 on 2024-08-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0037_remove_occupationalhealthsafety_incidentlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preconstructionstage',
            name='CRZClearanceDocuments',
        ),
        migrations.RemoveField(
            model_name='preconstructionstage',
            name='ForestClearanceDocuments',
        ),
        migrations.RemoveField(
            model_name='preconstructionstage',
            name='PermissionForFellingOfTreesDocuments',
        ),
        migrations.RemoveField(
            model_name='preconstructionstage',
            name='ShiftingofUtilitiesDocuments',
        ),
    ]
