# Generated by Django 4.1.5 on 2024-08-06 08:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0038_remove_preconstructionstage_crzclearancedocuments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstructionstage',
            name='CRZClearanceDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='ForestClearanceDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='PermissionForFellingOfTreesDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='ShiftingofUtilitiesDocuments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
