# Generated by Django 4.1.5 on 2024-08-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0039_preconstructionstage_crzclearancedocuments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionstage',
            name='AuthorizationForCollectionDisposalManagementDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='AuthorizationForSolidWasteDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='ConsentToDisposalOfsewagefromLabourCampsDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='ConsenttToEstablishOoperateDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='DisposalOfBituminousAndOtherWasteDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='PermissionForGroundWaterWithdrawalDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='PermissionForSandMiningFromRiverbedDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='PollutionUnderControlCertificateDocuments',
        ),
        migrations.RemoveField(
            model_name='constructionstage',
            name='RoofTopRainWaterHarvestingDocuments',
        ),
    ]
