# Generated by Django 4.1.5 on 2024-08-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0041_constructionstage_authorizationforcollectiondisposalmanagementdocuments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traning',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='traning',
            name='photographs',
        ),
    ]
