# Generated by Django 4.1.5 on 2024-08-07 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0042_remove_traning_documents_remove_traning_photographs'),
    ]

    operations = [
        migrations.AddField(
            model_name='traning',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='traning',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
