# Generated by Django 4.1.5 on 2024-08-27 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0044_remove_occupationalhealthsafety_accidentalcheckcondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='photographs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, default=list, size=None),
        ),
    ]
