# Generated by Django 4.1.5 on 2024-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0045_occupationalhealthsafety_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='labourCampId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhealthsafety',
            name='labourCampName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
