# Generated by Django 4.1.5 on 2024-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0046_occupationalhealthsafety_labourcampid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionstage',
            name='packages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconstructionstage',
            name='packages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
