# Generated by Django 4.1.5 on 2024-10-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0047_constructionstage_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traning',
            name='conductDate',
        ),
        migrations.RemoveField(
            model_name='traning',
            name='traningDate',
        ),
        migrations.AddField(
            model_name='traning',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
