# Generated by Django 4.1.5 on 2023-09-04 07:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectaffectedperson',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('pap_id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'projectAffectedPerson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RehabilitatedPap',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('pap_id', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('date_ident', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
