# Generated by Django 4.1.5 on 2023-09-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehabilitatedpap',
            options={'managed': False},
        ),
    ]
