# Generated by Django 4.1.5 on 2023-09-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0002_alter_rehabilitatedpap_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rehabilitatedpap',
            table='rehabilitated_PAP',
        ),
    ]
