# Generated by Django 4.1.5 on 2023-09-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0003_alter_rehabilitatedpap_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rehabilitatedpap',
            table='rehabilitations',
        ),
    ]
