# Generated by Django 4.1.5 on 2024-08-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0004_alter_rehabilitatedpap_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RehabilitatedPap',
        ),
    ]
