# Generated by Django 4.1.5 on 2024-09-16 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0005_delete_rehabilitatedpap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStartEndPoints',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('names', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'all_start_end_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaAlignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa08Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_08_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa09Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_09_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa10Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_10_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa11Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_11_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa12Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_12_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MmrdaCa54Alignment4326',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mmrda_ca_54_alignment_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa08MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_08_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa08StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_08_start_end_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa09MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_09_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa09StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_09_start_end_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa10MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_10_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa10StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_10_start_end_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa11MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_11_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa11StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_11_start_end_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa12MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_12_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa12StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_12_start_end_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa54MetroStations',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_54_metro_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PackageCa54StartEndPoint',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'package_ca_54_start_end_point',
                'managed': False,
            },
        ),
    ]
