# Generated by Django 4.1.5 on 2024-09-18 10:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GIS', '0006_allstartendpoints_mmrdaalignment4326_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEndPoints',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'start_end_points',
                'managed': False,
            },
        ),
    ]
